# fly.toml app configuration file generated for discobot-5023 on 2023-05-07T20:46:09+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "discobot-5023"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true
